language: python
python:
    - '2.7'

# get pip up-to-date
install:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - nose2 -v --with-coverage --coverage midnite
    - flake8 tests pymidnite setup.py

after_success:
    coveralls

notifications:
    email: false
